#!/usr/bin/env python3
"""Generate and validate all bundled BankerDeck example specs under temp/."""

from __future__ import annotations

import json
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "banker-deck" / "assets"
TEMP_OUTPUT = ROOT / "temp" / "generated"

sys.path.insert(0, str(ROOT / "banker-deck" / "scripts"))
from generate_banker_deck import THEMES, write_pptx  # noqa: E402


def validate_pptx(path: Path, expected_slides: int) -> None:
    with zipfile.ZipFile(path) as zf:
        names = zf.namelist()
        slide_names = sorted(
            name
            for name in names
            if name.startswith("ppt/slides/slide") and name.endswith(".xml")
        )
        if len(slide_names) != expected_slides:
            raise AssertionError(f"{path.name}: expected {expected_slides} slides, found {len(slide_names)}")
        required = {
            "[Content_Types].xml",
            "_rels/.rels",
            "ppt/presentation.xml",
            "ppt/_rels/presentation.xml.rels",
            "ppt/theme/theme1.xml",
        }
        missing = required.difference(names)
        if missing:
            raise AssertionError(f"{path.name}: missing package files {sorted(missing)}")
        for name in names:
            if name.endswith(".xml"):
                ET.fromstring(zf.read(name))


def validate_theme_profile(path: Path, theme_name: str) -> None:
    theme = THEMES[theme_name]
    with zipfile.ZipFile(path) as zf:
        xml_blob = "\n".join(
            zf.read(name).decode("utf-8")
            for name in zf.namelist()
            if name.endswith(".xml")
        )
    required_tokens = [
        theme["primary"],
        theme["secondary"],
        theme["font"],
        theme["profile"],
        theme["tone"],
        theme["density"],
        theme["chart_style"],
    ]
    for token in required_tokens:
        if token not in xml_blob:
            raise AssertionError(f"{path.name}: missing theme token for {theme_name}: {token}")


def main() -> None:
    TEMP_OUTPUT.mkdir(parents=True, exist_ok=True)
    specs = sorted(ASSETS.glob("*.json"))
    if not specs:
        raise SystemExit("No example specs found.")

    for spec_path in specs:
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
        output = TEMP_OUTPUT / f"{spec_path.stem}.pptx"
        write_pptx(spec, output)
        validate_pptx(output, len(spec.get("slides", [])))
        print(f"ok {spec_path.name} -> {output.relative_to(ROOT)}")

    for theme_name in sorted(THEMES):
        spec = {
            "title": f"{theme_name} theme smoke test",
            "subtitle": "Theme coverage generated by BankerDeck tests",
            "theme": theme_name,
            "footer": f"BankerDeck | {theme_name}",
            "slides": [
                {
                    "type": "title",
                    "title": f"{theme_name} theme smoke test",
                    "subtitle": "Editable PPTX theme validation"
                },
                {
                    "type": "summary",
                    "title": f"{theme_name} renders editable BankerDeck objects with the selected theme",
                    "bullets": [
                        "Title, message cards, source notes, and footer are PowerPoint XML shapes.",
                        "Theme palette is applied through editable text boxes, fills, and rules.",
                        "Package structure and slide XML are validated after generation."
                    ],
                    "source": "Source: BankerDeck automated smoke test."
                },
                {
                    "type": "table",
                    "title": f"{theme_name} table module remains editable and parseable",
                    "headers": ["Check", "Expected"],
                    "rows": [
                        ["Theme ID", theme_name],
                        ["Editable objects", "Text boxes, shapes, and table cells"],
                        ["Validation", "PPTX package XML parse"],
                    ],
                    "source": "Source: BankerDeck automated smoke test."
                }
            ]
        }
        output = TEMP_OUTPUT / "themes" / f"{theme_name}.pptx"
        output.parent.mkdir(parents=True, exist_ok=True)
        write_pptx(spec, output)
        validate_pptx(output, len(spec["slides"]))
        validate_theme_profile(output, theme_name)
        print(f"ok theme {theme_name} -> {output.relative_to(ROOT)}")

    print(f"generated {len(specs)} example deck(s) and {len(THEMES)} theme smoke deck(s) under {TEMP_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
